### PR TITLE
SGT-52-1

### PR DESCRIPTION
**Pull request by kareemthedeveloper**
Used the member recordType to replace any reference to the Member object. Added record types, page layouts and fields. Replaced relationships to adjust with the new architecture. Deleted the workflow rule and the Member object.

### CODE REVIEW

**Review by SimonSSSSF — CHANGES_REQUESTED** [review]
WorkoutDistributor must specify record type in query for contacts
BenchmarkTriggerUtility contains hardcoded id

**Comment by kareemthedeveloper** [comment]
By default when you create a record with the specified fields of a record-type, it will use that record-type of the Object to insert it in the database regarding the workout distributor class. I can remove the hard coded Id for sure

**Comment by kareemthedeveloper** [comment]
Made the changes requested and cleaned up the code a bit. Working with maps makes the code more accurate

**Review by SimonSSSSF — COMMENTED** [review]
The BenchmarkTriggerUtility class still has a hard-coded Id for the record type

**Comment by kareemthedeveloper** [comment]
Just removed the hardcoded Id. Lmk if there needs to be further changes!!

**Comment by kareemthedeveloper** [comment]
Will create a new branch to not conflict with Lee's changes

**Pull request closed without merging**
